
USE HR_MGMT 
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INTEGER NOT NULL,
DEPARTMENT_NAME VARCHAR(255) NOT NULL, LOCATION_ID INTEGER)
-- CREATING DEPARTMENTS TABLE

INSERT INTO DEPARTMENTS VALUES(99,'SALES',01)


SELECT * FROM DEPARTMENTS
INSERT INTO EMPLOYEES VALUES(112, 'ANWESH', 'MAHAJAN', 'AM@ROCK.COM', '2023-02-01', 'CEO', 43, 221, 231)
SELECT DISTINCT LAST_NAME FROM EMPLOYEES 

INSERT INTO LOCATIONS VALUES(10,'DSD_CHOWK',443402,'JALGAON','MAHARASHTRA')
SELECT * FROM LOCATIONS

INSERT INTO JOBS VALUES('CEO', 'CEO',12,43)
SELECT * FROM JOBS
CREATE TABLE EMPLOYEES (EMPLOYEE_ID INTEGER NOT NULL, FIRST_NAME VARCHAR(255) 
NOT NULL, LAST_NAME VARCHAR(255) NOT NULL,EMAIL VARCHAR(255) NOT NULL, HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR(255) NOT NULL, SALARY DECIMAL(8,2),	DEPARTMENT_ID INTEGER )
-- CREATING EMPLOYEES TABLE

CREATE TABLE JOBS (JOB_ID VARCHAR(255) NOT NULL, JOB_TITLE VARCHAR(255) NOT NULL,
MIN_SALARY INTEGER, MAX_SALARY INTEGER)
-- CREATING JOBS TABLE

CREATE TABLE LOCATIONS (LOCATION_ID INTEGER NOT NULL, STREET_ADDRESS VARCHAR(255),
POSTAL_CODE VARCHAR(255), CITY VARCHAR(255) NOT NULL, STATE_PROVIENCE VARCHAR(255))
-- CREATING LOCATIONS TABLE

ALTER TABLE EMPLOYEES ADD PHONE_NUMBER VARCHAR(255)
--ADDING COLUMN TO EMPLOYEES

UPDATE EMPLOYEES SET PHONE_NUMBER = '123' WHERE PHONE_NUMBER is null
--UPDATING PHONE NUMBER

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID='401'

SELECT FIRST_NAME FROM EMPLOYEES WHERE SALARY > '10000'


ALTER TABLE DEPARTMENTS ADD PRIMARY KEY(DEPARTMENT_ID)
ALTER TABLE EMPLOYEES ADD PRIMARY KEY(EMPLOYEE_ID)
ALTER TABLE JOBS ADD PRIMARY KEY(JOB_ID)
ALTER TABLE LOCATIONS ADD PRIMARY KEY(LOCATION_ID)

ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID)
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)




DROP TABLE DEPARTMENTS
DROP TABLE EMPLOYEES
DROP TABLE JOBS
DROP TABLE LOCATIONS

SELECT * FROM JOBS

SELECT name, database_id, create_date  
FROM sys.databases; 

SELECT
  EXTRACT(LOCATION_ID FROM LOCATIONS) AS year,
  SUM(money) AS money_earned
FROM LOCATIONS
GROUP BY EXTRACT(year FROM transaction_date);
