CREATE DATABASE HR_MGMT

USE HR_MGMT 
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INTEGER NOT NULL,
DEPARTMENT_NAME VARCHAR(255) NOT NULL, LOCATION_ID INTEGER)
-- CREATING DEPARTMENTS TABLE

INSERT INTO DEPARTMENTS VALUES(102, 'CS',21)

INSERT INTO EMPLOYEES VALUES(401, 'GAURAV', 'AHIR', 'GAURAV@ROCK.COM', '2023-02-01', 'GET', 35444, 3464, 32224)

INSERT INTO JOBS VALUES('GET', 'TRAINEE_ENGINEER',453,4353)

CREATE TABLE EMPLOYEES (EMPLOYEE_ID INTEGER NOT NULL, FIRST_NAME VARCHAR(255) 
NOT NULL, LAST_NAME VARCHAR(255) NOT NULL,EMAIL VARCHAR(255) NOT NULL, HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR(255) NOT NULL, SALARY DECIMAL(8,2),	DEPARTMENT_ID INTEGER )
-- CREATING EMPLOYEES TABLE

CREATE TABLE JOBS (JOB_ID VARCHAR(255) NOT NULL, JOB_TITLE VARCHAR(255) NOT NULL,
MIN_SALARY INTEGER, MAX_SALARY INTEGER)
-- CREATING JOBS TABLE

CREATE TABLE LOCATIONS (LOCATION_ID INTEGER NOT NULL, STREET_ADDRESS VARCHAR(255),
POSTAL_CODE VARCHAR(255), CITY VARCHAR(255) NOT NULL, STATE_PROVIENCE VARCHAR(255))
-- CREATING LOCATIONS TABLE

ALTER TABLE EMPLOYEES ADD PHONE_NUMBER VARCHAR(255)
--ADDING COLUMN TO EMPLOYEES

UPDATE EMPLOYEES SET PHONE_NUMBER = 123 WHERE PHONE_NUMBER is null
--UPDATING PHONE NUMBER

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 401

SELECT FIRST_NAME FROM EMPLOYEES WHERE SALARY>10000

ALTER TABLE DEPARTMENTS ADD PRIMARY KEY(DEPARTMENT_ID)
ALTER TABLE EMPLOYEES ADD PRIMARY KEY(EMPLOYEE_ID)
ALTER TABLE JOBS ADD PRIMARY KEY(JOB_ID)
ALTER TABLE LOCATIONS ADD PRIMARY KEY(LOCATION_ID)

ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID)
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPRTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)


DROP TABLE DEPARTMENTS
DROP TABLE EMPLOYEES
DROP TABLE JOBS
DROP TABLE LOCATIONS



select REPLACE('gaurav ahir','rav','var')
select SIGN(+23)
ALTER TABLE EMPLOYEES ADD PRIMARY KEY(EMPLOYEE_ID)

alter table employees add roll_no integer


